# Generated by Django 5.1.6 on 2025-02-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingevent',
            name='event_code',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
