# Generated by Django 5.1.6 on 2025-02-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0002_plantingevent_event_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('binomial', models.CharField(default='', max_length=1000)),
                ('needs_cold_stratify', models.BooleanField(default=False)),
                ('needs_indoor_sow', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='plantingevent',
            name='event_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='PlantSpeciesColdStratify',
            fields=[
                ('plantspecies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plantingcalendarapp.plantspecies')),
                ('cold_stratify_days_before_transplant', models.IntegerField()),
                ('transplant_days_before_last_frost', models.IntegerField(default=0)),
            ],
            bases=('plantingcalendarapp.plantspecies',),
        ),
        migrations.CreateModel(
            name='PlantSpeciesDirectSow',
            fields=[
                ('plantspecies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plantingcalendarapp.plantspecies')),
                ('sow_days_before_last_frost', models.IntegerField()),
            ],
            bases=('plantingcalendarapp.plantspecies',),
        ),
        migrations.CreateModel(
            name='PlantSpeciesIndoorSow',
            fields=[
                ('plantspecies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plantingcalendarapp.plantspecies')),
                ('indoor_sow_days_before_last_frost', models.IntegerField()),
            ],
            bases=('plantingcalendarapp.plantspecies',),
        ),
    ]
