# Generated by Django 5.1.6 on 2025-02-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0003_plantspecies_alter_plantingevent_event_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='website',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
