# Generated by Django 5.1.6 on 2025-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0004_plantspecies_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantspeciesindoorsow',
            old_name='indoor_sow_days_before_last_frost',
            new_name='indoor_sow_days_before_last_frost_max',
        ),
        migrations.AddField(
            model_name='plantspeciesindoorsow',
            name='indoor_sow_days_before_last_frost_min',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
