# Generated by Django 5.1.6 on 2025-02-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0005_rename_indoor_sow_days_before_last_frost_plantspeciesindoorsow_indoor_sow_days_before_last_frost_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingevent',
            name='event_type',
            field=models.CharField(choices=[('INDOOR', 'Indoor sow'), ('DIRECT', 'Direct sow outdoors'), ('TRANSPLANT', 'Transplant outdoors'), ('COLD_STRATIFY', 'Cold stratify')], default='DIRECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantingevent',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plantingevent',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='GrowerCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('last_frost_date', models.DateTimeField()),
                ('first_frost_date', models.DateTimeField()),
                ('station_id', models.IntegerField()),
                ('usda_hardiness_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plantingcalendarapp.usdahardinesszone')),
            ],
        ),
        migrations.CreateModel(
            name='GrowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plantingcalendarapp.growercalendar')),
                ('plant_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plantingcalendarapp.plantspecies')),
            ],
        ),
        migrations.AddField(
            model_name='plantingevent',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plantingcalendarapp.growerplant'),
        ),
    ]
