# Generated by Django 5.1.6 on 2025-02-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0006_plantingevent_event_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantingEvent',
            new_name='GrowerPlantingEvent',
        ),
    ]
