# Generated by Django 5.1.6 on 2025-02-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0007_rename_plantingevent_growerplantingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='growercalendar',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plantingcalendarapp.grower'),
        ),
        migrations.AlterUniqueTogether(
            name='growercalendar',
            unique_together={('grower', 'station_id')},
        ),
    ]
