# Generated by Django 5.1.6 on 2025-02-13 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0008_grower_growercalendar_grower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growerplantingevent',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plantingcalendarapp.growercalendar'),
        ),
        migrations.AlterUniqueTogether(
            name='growerplantingevent',
            unique_together={('plant', 'event_type')},
        ),
    ]
