# Generated by Django 5.1.6 on 2025-02-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0009_growerplantingevent_calendar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='growerplant',
            unique_together={('grower_calendar', 'plant_species')},
        ),
    ]
