# Generated by Django 5.1.6 on 2025-02-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0010_alter_growerplant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='can_direct_sow',
            field=models.BooleanField(default=False),
        ),
    ]
