# Generated by Django 5.1.6 on 2025-02-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantingcalendarapp', '0011_plantspecies_can_direct_sow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantspeciesdirectsow',
            old_name='sow_days_before_last_frost',
            new_name='sow_weeks_before_last_frost',
        ),
        migrations.RenameField(
            model_name='plantspeciesindoorsow',
            old_name='indoor_sow_days_before_last_frost_max',
            new_name='indoor_sow_weeks_before_last_frost_max',
        ),
        migrations.RenameField(
            model_name='plantspeciesindoorsow',
            old_name='indoor_sow_days_before_last_frost_min',
            new_name='indoor_sow_weeks_before_last_frost_min',
        ),
    ]
